#!/bin/bash
set -Eeuo pipefail

CHUTNEY="${CHUTNEY:-$PWD/chutney}"
CHUTNEY_TOR="$(which tor)"
CHUTNEY_TOR_GENCERT="$(which tor-gencert)"
CHUTNEY_DNS_CONF="/etc/resolv.conf" # default
export CHUTNEY CHUTNEY_TOR CHUTNEY_TOR_GENCERT CHUTNEY_DNS_CONF
CHUTNEY_NET="networks/basic"

function chutney()
{
    "$CHUTNEY" "$@"
}

function cleanup()
{
    trap - EXIT
    echo -e "Exiting...\n\n"
    chutney stop 

    tput rmcup
}

tput smcup
trap cleanup EXIT

chutney configure $CHUTNEY_NET 
chutney start $CHUTNEY_NET 
chutney status $CHUTNEY_NET 

ports="$(
    cat "$(dirname "$CHUTNEY")/net/nodes/"*"/torrc" | \
    grep -E "^(Socks|Or|Dir|Control)Port [0-9]*$" | grep -v " 0$")"

echo -e "\n"
for flavor in Control Dir Or Socks
do
    echo "${flavor}Ports: $(
        (grep "$flavor"|grep -Eo "[0-9]*"|tr "\n" " ") <<< "$ports")"
done

echo -en "\nPress return to shutdown chutney... "
read && cleanup
